### ISSUE TITLE
Chapter 20. 마이크로서비스 모니터링 🎉 

### ISSUE THREAD

**Issue by minkukjo** [DevSprout/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#17]
🎉 완강🎉

**Comment by minkukjo** [comment]
## 느낀 점
- 서킷브레이커 매트릭 정보를 그라파나에서 보여줄 수 있다고 한다. 이러면 모니터링 하기가 한결 수월할 듯 하다. (안써봐서 몰랐음.. )

## 질문
- 1 : 마이크로미터 라이브러리 의존성을 추가해주고, k8s 파드에 아래와 같은 애노테이션을 추가해준다.
```yaml
annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "4004"
  prometheus.io/scheme: http
  prometheus.io/path: "/actuator/prometheus"
```
- 거기다가 application.yaml (공통 구성 파일)에 다음과 같은 항목을 추가하면 메트릭에 앱 이름이 추가되며 이 값이 레이블 값으로 설정된다.
```yaml
management.metrics.tags.application: ${spirng.application.name}
```

- 2: 위에서 설명한대로 메트릭에 레이블이 추가되서 시계열 데이터를 식별하는 식별자값으로 정의해서 쿼리나 집계할 때 사용할 수 있다.

- 3: 그라파나

- 4: (여기선) 키알리

- 5: 단순히 값이 증가하는 재시도 매트릭 정보 보다는 초당 실패율로 환산해서 매 초마다 실패율을 보이게 하는 것이 더 매력적인 모니터링 방법이다.

- 6 : API 실패가 발생해서 서킷브레이커가 열림 상태가 되었고 이후 반열림 상태가 되었으며 얼마 후 해당 API가 성공해서 다시 닫힘 상태가 되었다.
